---
stages:
  # - test
  - release

before_script:
  - python --version
  - pip --version


# test:3.5:
#   image: python:3.5-alpine
#   script:
#   - apk add py-pip python3-dev
#   - pip3 install -r requirements_test.txt
#   - pytest --version
#   - tox -e py35
#
# test:3.6:
#   image: python:3.6-alpine
#   script:
#   - apk add py-pip python3-dev
#   - pip3 install -r requirements_test.txt
#   - pytest --version
#   - tox -e py36
#
# test:3.7:
#   image: python:3.7-alpine
#   script:
#   - apk add py-pip python3-dev
#   - pip3 install -r requirements_test.txt
#   - pytest --version
#   - tox -e py37

test_release:
  stage: release
  image: python:3.7-alpine
  script:
  - pip install twine
  - rm -rf dist
  # - export TWINE_USERNAME=$PYPI_TEST_USER
  # - export TWINE_PASSWORD=$PYPI_TEST_PASSWD
  - echo "[distutils]" >> ~/.pypirc
  - echo "index-servers=" >> ~/.pypirc
  - echo "    pypi" >> ~/.pypirc
  - echo "    testpypi" >> ~/.pypirc
  - echo "" >> ~/.pypirc
  - echo "[testpypi]" >> ~/.pypirc
  - echo "repository: ${PYPI_TEST_REPO}" >> ~/.pypirc
  - echo "username: ${PYPI_TEST_USER}" >> ~/.pypirc
  - echo "password: ${PYPI_TEST_PASSWD}" >> ~/.pypirc
  - python3 setup.py check sdist bdist
  - python setup.py sdist bdist_wheel
  - twine upload -r testpypi dist/*.tar.gz
  only:
    - /^v\d+\.\d+\.\d+([abc]\d*)?$/  # PEP-440 compliant

# release:
#   stage: release
#   image: python:3.7-alpine
#   script:
#   - pip install twine
#   - rm -rf dist
#   # - export TWINE_USERNAME=$PYPI_USER
#   # - export TWINE_PASSWORD=$PYPI_PASSWD
#   - echo "[distutils]" >> ~/.pypirc
#   - echo "index-servers=" >> ~/.pypirc
#   - echo "    pypi" >> ~/.pypirc
#   - echo "    testpypi" >> ~/.pypirc
#   - echo "" >> ~/.pypirc
#   - echo "[pypi]" >> ~/.pypirc
#   - echo "${PYPI_REPO}" >> ~/.pypirc
#   - echo "${PYPI_USER}" >> ~/.pypirc
#   - echo "${PYPI_PASSWD}" >> ~/.pypirc
#   - python3 setup.py check sdist bdist  # This will fail if your creds are bad.
#   - python setup.py sdist bdist_wheel
#   - twine upload -r pypi dist/*.tar.gz
#   only:
#     tags:
#       - /^v\d+\.\d+\.\d+([abc]\d*)?$/  # PEP-440 compliant


# test:3.6:
#   image: python:3.6-stretch
#   script:
#   - apt-get update -yq
#   - apt-get install -y python3-pip python3-dev
#   - pip3 install -r requirements_test.txt
#   - pytest --version
#   # - pytest
#   # - pytest -v --cov=YesssSMS tests
#   # - pytest --cov=YesssSMS --cov-report annotate tests
#   # - cat YesssSMS/YesssSMS.py,cover
#   - tox -e py36
#   # or
#   # - pytest --cov=YesssSMS -cov-report html tests
#   # publish html to webserver
