---
stages:
  - test
  - release

before_script:
  - python --version
  - pip --version


test:3.5:
  image: python:3.5-alpine
  script:
  - apk add py-pip python3-dev
  - pip3 install -r requirements_test.txt
  - pytest --version
  - tox -e py35

test:3.6:
  image: python:3.6-alpine
  script:
  - apk add py-pip python3-dev
  - pip3 install -r requirements_test.txt
  - pytest --version
  - tox -e py36

test:3.7:
  image: python:3.7-alpine
  script:
  - apk add py-pip python3-dev
  - pip3 install -r requirements_test.txt
  - pytest --version
  - tox -e py37

test_release:
  stage: release
  image: python:3.7-alpine
  script:
  - pip install requests
  - |2
    python3 -c 'import sys as s; import requests as r; import YesssSMS;
    v = YesssSMS.YesssSMS().version()
    g = r.get("https://test.pypi.org/project/YesssSMS/"+v+"/");
    if g.status_code == 200:
      print("{} already released".format(v))
      s.exit(-1)' || exit 0
  - pip install twine
  - rm -rf dist
  - echo "[distutils]" >> ~/.pypirc
  - echo "index-servers=" >> ~/.pypirc
  - echo "    pypi" >> ~/.pypirc
  - echo "    testpypi" >> ~/.pypirc
  - echo "" >> ~/.pypirc
  - echo "[testpypi]" >> ~/.pypirc
  - |2
    echo "repository: ${PYPI_TEST_REPO}" >> ~/.pypirc
    echo "username: ${PYPI_TEST_USER}" >> ~/.pypirc
    echo "password: ${PYPI_TEST_PASSWD}" >> ~/.pypirc
  - python3 setup.py check sdist bdist_wheel
  - ls -lha dist
  - twine upload  --verbose -r testpypi dist/*.tar.gz dist/*.whl
  only:
    - /^test_v\d+\.\d+\.\d+([abc]\d*)?$/  # PEP-440 compliant

release:
  stage: release
  image: python:3.7-alpine
  script:
  - pip install requests
  - |2
    python3 -c 'import sys as s; import requests as r; import YesssSMS;
    v = YesssSMS.YesssSMS().version()
    g = r.get("https://pypi.org/project/YesssSMS/"+v+"/");
    if g.status_code == 200:
      print("{} already released".format(v))
      s.exit(-1)' || exit 0
  - pip install twine
  - rm -rf dist
  - echo "[distutils]" >> ~/.pypirc
  - echo "index-servers=" >> ~/.pypirc
  - echo "    pypi" >> ~/.pypirc
  - echo "" >> ~/.pypirc
  - echo "[pypi]" >> ~/.pypirc
  - |2
    echo "username: ${PYPI_USER}" >> ~/.pypirc
    echo "password: ${PYPI_PASSWD}" >> ~/.pypirc
  - python3 setup.py check sdist bdist_wheel
  - ls -lha dist
  - twine upload  --verbose -r pypi dist/*.tar.gz dist/*.whl
  only:
    - /^v\d+\.\d+\.\d+([abc]\d*)?$/  # PEP-440 compliant


# test:3.6:
#   image: python:3.6-stretch
#   script:
#   - apt-get update -yq
#   - apt-get install -y python3-pip python3-dev
#   - pip3 install -r requirements_test.txt
#   - pytest --version
#   # - pytest
#   # - pytest -v --cov=YesssSMS tests
#   # - pytest --cov=YesssSMS --cov-report annotate tests
#   # - cat YesssSMS/YesssSMS.py,cover
#   - tox -e py36
#   # or
#   # - pytest --cov=YesssSMS -cov-report html tests
#   # publish html to webserver
